config/routes.rb
Rails.application.routes.draw do
  get 'searches/new'

  resources :searches

  root 'searches#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
	validates :query, presence: true, 
		length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def new
		#instantiate new Search instance variable
  		@search = Search.new
  	end

  	def create
  		#instantiate new Search instance variable
  		@search = Search.new(params.require(:search).permit(:query))

  		#check to see if any errors were thrown server-side
  		#if error, set flash[:notice] and redirect_back
  		#else, start the Twitter search
  		if !@search.save
  			flash[:notice] = "ERROR: check your input"
  			redirect_back(fallback_location: root_path)
		else
			#collect the popular tweets, limit count to 100
			begin
			  	tweets = Twitter::Client::Instance.search(@search.query, result_type: "popular").take(100).collect 
			rescue Twitter::Error::Forbidden => e
				flash[:notice] = "ERROR: Twitter search input error"
  			end

			#check to see of there are any tweets collected
			if !tweets.nil? && tweets.count > 0
				#for each tweet, check for any user mentions and hashtags
				#if there are any, place them into their respective hash
				#and keep count, not allowing any duplicates
				#if there are no user mentions or hashtags, empty the variable
				tweets.each do |tweet|
					if !tweet.user_mentions.empty?
						tweet.user_mentions.each do |i| 
							if Twitter::Results.userMentions.key?("@" + i.screen_name)
								Twitter::Results.userMentions["@" + i.screen_name] += 1
							else
								Twitter::Results.userMentions["@" + i.screen_name] = 1
							end #if-else
						end #each
					else
						Twitter::Results.userMentions.clear
					end #if-else
					if !tweet.hashtags.empty?
						tweet.hashtags.each do |i|
							if Twitter::Results.hashTags.key?("#" + i.text)
								Twitter::Results.hashTags["#" + i.text] += 1
							else
								Twitter::Results.hashTags["#" + i.text] = 1
							end #if-else
						end #each
					else
						Twitter::Results.hashTags.clear
					end
				end #if-else
			else
				Twitter::Results.userMentions.clear
				Twitter::Results.hashTags.clear
			end #if

			#Go ahead and sort the hashes in descending order for view display
			Twitter::Results.sort_hash
			
			#hack to pass the search query into the view
			session[:query] = @search.query
			
			#once complete, redirect back to the same page
			redirect_back fallback_location: { action: "new" }
		end	  
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>TT_Analyzer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/searches/new.html.erb
<%= stylesheet_link_tag "style" %>
<div class="row">
  <div id="header-form" class="col-sm-12">
    <h1>Twitter Trend Analyzer</h1>
    <%= form_with scope: :search, url: searches_path, local: true do |form| %>
	  <%= form.text_field :query, id: "query" , class: "form-control", placeholder: "e.g. tuns.pk, @tunespeak, #metallica" %>
	  <%= form.submit "Analyze", id: "submit", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

<% if flash[:notice] %>
    <div id="error_explanation">
      <h6>
        <%= flash[:notice] %>
      </h6>
    </div>
<% end %>

<h4>Showing results for: <%= session[:query].inspect %></h4></br>

<h5>@UserMentions</h5>
<table class="table">
<% if !Twitter::Results.userMentions.empty? %>	
	<% Twitter::Results.userMentions.each do |key, value| %>
	    <tr>
	      	<td class="hash-value"><%= "#{value}" %></td>
	      	<td class="hash-key"><%= "#{key}" %></td>
	    </tr>
	<% end %>
<% else %>
	<tr>
      	<td>No results</td>
      	<td>-</td>
    </tr>
<% end %>
</table>

<h5>#Hashtags</h5>
<table class="table">
<% if !Twitter::Results.hashTags.empty? %>
	<% Twitter::Results.hashTags.each do |key, value| %>
	    <tr>
	      	<td class="hash-value"><%= "#{value}" %></td>
	      	<td class="hash-key"><%= "#{key}" %></td>
	    </tr>
    <% end %>
<% else %>
	<tr>
      	<td>No results</td>
      	<td>-</td>
    </tr>
<% end %>
</table>